apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic-container
          image: 730335384723.dkr.ecr.ap-south-1.amazonaws.com/my-hf-model:latest
          ports:
            - containerPort: 8080
